services:
  react-todo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - react_todo_node_modules:/app/node_modules
      - react_todo_pnpm_store:/app/.pnpm-store
    container_name: react-todo

    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  react_todo_node_modules:
  react_todo_pnpm_store:


